[tools]
"aqua:1password/cli" = "2.32.0"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:FiloSottile/age" = "latest"
"aqua:derailed/k9s" = "latest"
"aqua:eza-community/eza" = "0.23.4"
"aqua:jdx/usage" = "latest"
"aqua:kubernetes/kubernetes/kubectl" = "latest"
"aqua:siderolabs/talos" = "latest"
"aqua:sst/opencode" = "1.0.78"
"aqua:starship/starship" = "latest"
